version: '3'

dotenv: []

vars:
  APP_NAME: todoapp
  APP_VERSION: 0.0.1-SNAPSHOT

tasks:
  # Default task
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  # Build tasks for each profile (just for different JAR names)
  build:stdio:
    desc: "Build application for STDIO profile"
    cmds:
      - ./gradlew clean build -Pprofile=stdio -Pversion={{.APP_VERSION}}

  dev:sse:
    desc: "Run application in development mode with SSE profile"
    cmds:
      - ./gradlew bootRun --args='--spring.profiles.active=sse'
    interactive: true

  dev:streamable:
    desc: "Run application in development mode with Streamable profile"
    cmds:
      - ./gradlew bootRun --args='--spring.profiles.active=streamable'
    interactive: true

  dev:stateless:
    desc: "Run application in development mode with Streamable profile"
    cmds:
      - ./gradlew bootRun --args='--spring.profiles.active=stateless'
    interactive: true
